on:
  release:
    types: [created]

name: Publish to crates.io

permissions:
  contents: write

jobs:
  publish:
    name: Publish to cargo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        run: cargo test

      - name: Publish cumulo-dipa-derive
        run: cargo publish -p cumulo-dipa-derive --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for cumulo-dipa-derive to be available
        run: sleep 30

      - name: Publish cumulo-dipa
        run: cargo publish -p cumulo-dipa --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
